### ISSUE TITLE
Thoroughly review hiking app work and newbie progress

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#84]
## alexine, alexinedewit

Function: `multiply_four_numbers`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [x] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [x] : Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [x] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [x] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [x] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [x] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

Others:

 * [x] Alexine: set up correct git username, https://github.com/informalr/informalr/issues/85

## bara, barawaclawik

Function: `add_one`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [ ] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [ ] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [ ] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [ ] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [ ] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [ ] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [ ] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [ ] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

## claudio, janclod

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [x] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [x] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [x] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [x] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [x] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [ ] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

Other:

 * [ ] Visualize data on a map, https://github.com/informalr/informalr/issues/49
   comment at https://github.com/informalr/informalr/issues/49#issuecomment-717213366

I hope -after fixing these Issues- you will work on 'Create a stub for the Shiny app',
https://github.com/informalr/informalr/issues/50 . 
I predict @friesewoudloper will be working on this and I think she would enjoy you as
a teammate.

## frans

Function: `subtract_four_numbers`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [ ] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [x] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [x] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [x] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [x] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [ ] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

Other:

 * There has been a confusion between @fransbianchi and @bogeert, as they
   both worked on `subtract_four_numbers`. `subtract_four_numbers` is the
   function assigned to Frans however, so Frans can claim the 
   function as his (setting himself as the (second?) author), where
   Geert should still create the `subtract_three_numbers` function

## geert

Function: `subtract_three_numbers`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [x] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [x] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [x] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [x] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [x] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [x] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

Other:

 * First, merge your work to develop :+1:
 * There has been a confusion between @fransbianchi and @bogeert, as they
   both worked on `subtract_four_numbers`. `subtract_four_numbers` is the
   function assigned to Frans however, so Frans can claim the 
   function as his (setting himself as the (second?) author), where
   Geert should still create the `subtract_three_numbers` function

## jan

Function: `power_two_numbers`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [x] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [x] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [x] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [ ] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [x] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [ ] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

## lizzie

Unknown

## pamela

Function: `add_two`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [ ] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [ ] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [ ] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [ ] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [ ] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [ ] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

## stefano

Function: `divide_two_numbers`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [x] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [x] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [x] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [ ] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [x] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [ ] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

## willy

Function: `modulo_two_numbers`

 * [x] Create a Discord account, send Richel a Discord Friend Request: richelbilderbeek#9002, so he can add you to the tresinformal Discord group
 * [x] Create a GitHub account, share it with a team member so he/she can add you to the informalr team
 * [x] Do a trivial git push to master, https://github.com/informalr/informalr/issues/11
 * [x] Create your own branch using the GitHub web interface, https://github.com/informalr/informalr/issues/13
 * [x] Do a trivial git push to your branch, https://github.com/informalr/informalr/issues/15
 * [x] Write your first trivial code, https://github.com/informalr/informalr/issues/12
 * [x] Write happy-road test for function, https://github.com/informalr/informalr/issues/31
 * [x] Write the actual function, which assumes correct input, https://github.com/informalr/informalr/issues/32
 * [x] Write tests for function misuse, https://github.com/informalr/informalr/issues/34
 * [x] Write the actual function code, for incorrect input, https://github.com/informalr/informalr/issues/35
 * [x] Add a textual datafile to inst/extdata, https://github.com/informalr/informalr/issues/36

Others, using `https://github.com/issues?q=is%3Aopen+is%3Aissue+assignee%3Afriesewoudloper+archived%3Afalse`

 * Read public transportation data, 
   https://github.com/informalr/informalr/issues/48:
   still needed
 * Error: `create_map(png_filename = png_filename)` produced messages. 
   https://github.com/informalr/informalr/issues/76:
   fix or unassign or re-assign
 * Fix style of R/download_traffic_data.R,
   https://github.com/informalr/informalr/issues/80:
   seems fixed, well done!

I hope -after fixing these Issues- you will work on 'Create a stub for the Shiny app',
https://github.com/informalr/informalr/issues/50 . 
I predict @janclod will be working on this and I think he would enjoy you as
a teammate.

**Comment by richelbilderbeek** [comment]
Well done Richel :+1:
